### PR TITLE
Upgrade to Akka HTTP 10.1.5

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Oops

**Comment by ktoso** [comment]
Nope, you’d break the lagom interop story

**Comment by raboof** [comment]
@ktoso how so?

**Comment by raboof** [comment]
for akka-grpc we're already targeting lagom 1.5 which is on akka-http 10.1 - perhaps you were thinking of akka-management?

**Comment by ktoso** [comment]
Ah I see... sorry, I lumped them into the same bucket. But as this is a new feature we can target 1.5...

**Pull request closed without merging**
