### PR TITLE
Add links to example/quickstart projects

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by dwijnand** [comment]
Do we do any CI validation on docs, like link checking or something? Valid markdown checking?

**Comment by raboof** [comment]
we run 'paradox' in CI, which checks for dead `@ref` references but not dead external links

**Comment by dwijnand** [comment]
Then I guess you're clear to land this PR :)

**Comment by raboof** [comment]
well, if I can get CI to pass that is ;). (though it seems to fail on something unrelated - perhaps related to the upgrade of the jenkins slaves we just did?)

**Comment by raboof** [comment]
Jup: I updated my own machine from openjdk 8u171-b11 to openjdk 1.8.0_181 and can reproduce the error :(

**Comment by raboof** [comment]
```
java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Ljava/security/SecureRandom;Ljava/lang/String;IZ)V
        at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:787)
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:232)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:992)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:989)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1467)
        at akka.stream.impl.io.TLSActor.runDelegatedTasks(TLSActor.scala:404)
```

**Comment by raboof** [comment]
Related to https://github.com/jetty-project/jetty-alpn/issues/22

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
moved that particular jenkins job to the oracle jdk8 until ubuntu fix this issue.

**Comment by ignasi35** [comment]
Just got hit by this on a Docker container built using:

```
FROM openjdk:8
WORKDIR /opt/docker
...
```

**Comment by ignasi35** [comment]
> What a mess.

Yes.

--------------------------------------------

My current alternative is: 

https://github.com/playframework/play-scala-grpc-example/blob/30a5cca94e4135d74189f1ee7dbc2ca89801b28e/build.sbt#L26-L32

IIRC, `openjdk:8-alpine` failed to run `sbt-native-packager` scripts so I had to manually include `ExecCmd("RUN", "apk", "add", "--no-cache", "bash")`.

**Pull request merged**
