### PR TITLE
update scalapb and grpc denendencies

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by patriknw** [comment]
Thanks for contribution. 

Before merging we must setup cla and pr validation.

**Comment by raboof** [comment]
Yes, congrats on the first community contribution ;) - hang in there while we set things up.

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
(we're working out a problem with out cla-verifier, please hang in there ;) - change much appreciated!)

**Comment by ktoso** [comment]
CLA checker should work now

**Comment by raboof** [comment]
There it is! Thanks for the PR and for your patience :)

**Pull request merged**
