### PR TITLE
upgrade to sbt 1.2.7

### PR DESCRIPTION
**Pull request by mcanlas**

### CODE REVIEW

**Comment by dwijnand** [comment]
OK TO TEST

**Comment by dwijnand** [comment]
LOL, I can merge the PR, but I can't get CI to test it.  That's backwards 😆

**Comment by raboof** [comment]
PLS WHITELIST

**Comment by raboof** [comment]
OK TO TEST

**Comment by dwijnand** [comment]
How do I get "OK TO TEST" permissions?

I'm not entirely familiar with Jenkins GH plugin but "PLS WHITELIST" just allows the PR author's future PRs to immediate start testing, right?

**Comment by raboof** [comment]
Ah, PLS WHITELIST was indeed the wrong thing. I've added you to the list in Jenkins manually.

**Comment by dwijnand** [comment]
Thank you!

**Comment by mcanlas** [comment]
Might need a re-ping. The latest copy of the test failed because `java` couldn't be found, not sure why.

https://jenkins.akka.io:8498/job/akka-grpc-pr-validator/744/console

```
java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-oracle/bin/java" (in directory "/localhome/jenkinsakka/workspace/akka-grpc-pr-validator"): error=2, No such file or directory
```

Misconfigured node?

**Comment by dwijnand** [comment]
Hmm.  Maybe.  Let's try again:

retest this please

**Comment by mcanlas** [comment]
I'm going to update to 1.2.7 since it got released today. No release notes yet so no rush on merging.

**Pull request merged**
