### PR TITLE
Cross publish runtime for Scala 2.11

### LINKED ISSUE #345: Cross-build for Scala 2.11

### PR DESCRIPTION
**Pull request by 2m**
Also add a scripted test that verifies that correct runtime is added by the plugin.

Fixes #345

### CODE REVIEW

**Comment by dwijnand** [comment]
Why did Jenkins fail?

**Comment by 2m** [comment]
From the logs it seems that the `akka-grpc-plugin-tester-java / Compile / protocGenerate` task failed. It works on my machine so maybe it is intermittent. I'll try to restart the Jenkins job.

**Comment by 2m** [comment]
PLS BUILD

**Comment by 2m** [comment]
Ooh, it completed with passing grades after a restart!

**Pull request merged**
