### PR TITLE
Prefer linking the spec than the docs of an implementation

### PR DESCRIPTION
**Pull request by ignasi35**
The repo powering grpc.github.io seems to have been archived? 

https://github.com/grpc/grpc.github.io

### CODE REVIEW

**Review by raboof — APPROVED** [review]
:+1:

**Comment by raboof** [comment]
PLS BUILD

**Comment by ignasi35** [comment]
PLS BUILD

**Comment by raboof** [comment]
(jenkins was still merging to master, updated it to merge to the target branch instead - so this build should now succeed :+1: )

**Pull request merged**
