### PR TITLE
More idiomatic play integration #420

### PR DESCRIPTION
**Pull request by ctoomey**
Here's a draft, scala-only implementation of #420 that's built on top of the changes for #179 in PR #429.

Per discussion in #429 (which this was originally included in), I've improved the implementation of the Play action-returning version of the code to reuse the std. auto-generated handler rather than duplicate much of it (see `codegen/src/main/twirl/templates/PlayScala/RouterUsingActions.scala.txt`).

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by ctoomey** [comment]
@raboof @johanandren: I've made the requested changes so am ready to look at supporting java and the other build tools.

Please confirm you're good with this moving forward.

**Comment by raboof** [comment]
At a quick glance this looks good! Let's first focus on #429, and then when that's merged look into this more closely again.

**Comment by ctoomey** [comment]
@raboof @johanandren: This is ready for review. I see that tests and documentation are located in playframework/play-grpc. Is the process to release changes to akka-grpc first and then update/release playframework/play-grpc after?

**Comment by johanandren** [comment]
Sorry for late response, we've both been away from work recently. I'm not quite on top of where we are at with moving things over to that play module. 

Maybe it would be better to merge #429 and then complete the separation to the play repo and then do the play-idiomatics over there, to not stall that process more?

**Comment by ctoomey** [comment]
Agree that #429 is good to merge regardless of this PR as it's not Play-related.

I don't know what's going on with Play separation (what's the PR or issue?) but I'd really like for you to go ahead and merge this so that it doesn't require a bunch of rework after sitting around waiting for the Play separation effort. Merging this shouldn't make that effort any harder.

**Comment by raboof** [comment]
I think this now needs a rebase to bring it back up to date with the changes introduced as part of #429, right?

**Comment by ctoomey** [comment]
I couldn't figure out how to easily rebase my quite old branch, so I'm closing this PR in favor of the clean #534.

**Pull request closed without merging**
