### PR TITLE
feat: Native image metadata

### PR DESCRIPTION
**Pull request by johanandren**

### CODE REVIEW

**Comment by johanandren** [comment]
I don't think we need a separate test for Java, runtime is the same, differences are mostly about codegen and build tool plugins.

Passes locally but depends on https://github.com/akka/akka/pull/32308 and https://github.com/akka/akka-http/pull/4349 merged and released before it can go in.

**Comment by johanandren** [comment]
Green native-image tests in https://github.com/akka/akka-grpc/actions/runs/8069572819

**Comment by johanandren** [comment]
New green test run in https://github.com/akka/akka-grpc/actions/runs/8081995207

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
Green native-image test in https://github.com/akka/akka-grpc/actions/runs/8081995207

**Pull request merged**
