### PR TITLE
Don't update beyond scalatest 3.1

### PR DESCRIPTION
**Pull request by raboof**
Until akka updates, https://github.com/akka/akka/issues/29368

Replaces #1094

### CODE REVIEW

**Comment by raboof** [comment]
Before merging, we should double-check we don't have the problem identified in https://github.com/akka/akka/pull/29503

**Comment by raboof** [comment]
(checked, failures look OK)

**Review by ignasi35 — APPROVED** [review]

**Comment by ignasi35** [comment]
@raboof, https://github.com/akka/akka/pull/29503 is still unmerged but I understand it is safe to merge _this_ PR, right? It LGTM and I've approved. Feel free to press the buttons.

**Comment by raboof** [comment]
> [akka/akka#29503](https://github.com/akka/akka/pull/29503) is still unmerged but I understand it is safe to merge _this_ PR, right?

Exactly, this PR makes sure we don't update akka-grpc, which is what we want to do until we upgrade on the Akka side.

**Pull request merged**
