### PR TITLE
Add coursier cache

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by johanandren** [comment]
Oh wait, it's the other way around `~/.coursier/cache/`

**Comment by raboof** [comment]
Are you sure? e.g. https://github.com/scala/scala-xml/pull/357/files#r324386303

**Comment by johanandren** [comment]
That's where they live on my machine at least

**Comment by johanandren** [comment]
Ah, I see, nvm then I guess.

**Comment by johanandren** [comment]
Hah, actually on MacOS, after deleting `~/.courser` it now uses `~/Library/Caches/Coursier/` (which I guess is where MacOS wants it but still...).

**Comment by jrudolph** [comment]
> Hah, actually on MacOS, after deleting `~/.courser` it now uses `~/Library/Caches/Coursier/` (which I guess is where MacOS wants it but still...).

That behavior seems to be documented here: 

https://get-coursier.io/docs/cache.html#compatibility-with-former-versions

**Pull request merged**
