### PR TITLE
fix: multi project cross dependencies

### PR DESCRIPTION
**Pull request by eshepelyuk**
References #1054 

@raboof sorry
yet another fix for advanced cases, no tests for now :(

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by eshepelyuk** [comment]
@raboof will it be possible to merge this today ?

**Comment by raboof** [comment]
(not sure why the CLA bot is not responding, your CLA is of course :+1:)

**Comment by raboof** [comment]
> @raboof will it be possible to merge this today ?

Done!

**Comment by eshepelyuk** [comment]
Thank you !

**Pull request merged**
