### PR TITLE
Enable local storage of client tracing for Java and Scala clients #374

### LINKED ISSUE #374: Enable tracing for the generated clients
As the client api is currently netty based, we don't have access to the Akka HttpRequests and HttpResponses in the same way as we do for servers. This means we cannot add tracing info to the requests. Thankfully grpc-java and the netty client has OpenCensus tracing integration, it is just not enabled for the clients generated here.

Its a simple one liner to enable:
`.setSampledToLocalTracing(true)`

This would allow adding a module for [OpenCensus Scala for akka-grpc](https://github.com/census-ecosystem/opencensus-scala/issues/60), for tracing (and eventually Stats/ metrics as well) 

Is this okay to enable by default for generated clients?

Will add a PR for this and see what the consensus is.

### PR DESCRIPTION
**Pull request by aperkins1310**
Closes #374

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @aperkins1310,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Is there no overhead attached to enabling the tracing? (As in, will people who don't use it see a performance overhead from the setting being always on?)

**Comment by raboof** [comment]
I haven't found anything about how big the overhead is, but grpc-java and scalapb also enable this (hard-coded), so at least we're in good company...

**Pull request merged**
