### PR TITLE
Update protobuf gradle plugin to 0.8.11, require gradle 5.6.4

### PR DESCRIPTION
**Pull request by lukasito**
## Purpose

- support for gradle 6.x

## References

References #xxxx

## Changes

- increased gradle wrapper version to 5.6.4
- upgraded protobuf gradle plugin to 0.8.11
- added compatibility check when applying the plugin

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by raboof** [comment]
OK TO TEST

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lukasito** [comment]
Fixed stuff with author issues.

**Comment by lukasito** [comment]
any ideas why 
```
* What went wrong:

Could not determine the dependencies of task ':akka-grpc-gradle-plugin:compileJava'.

> Could not resolve all task dependencies for configuration ':akka-grpc-gradle-plugin:compileClasspath'.

   > Could not resolve com.google.protobuf:protobuf-gradle-plugin:0.8.11.

     Required by:

         project :akka-grpc-gradle-plugin

      > Could not resolve com.google.protobuf:protobuf-gradle-plugin:0.8.11.

         > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-gradle-plugin/0.8.11/protobuf-gradle-plugin-0.8.11.pom'.

            > Could not HEAD 'https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-gradle-plugin/0.8.11/protobuf-gradle-plugin-0.8.11.pom'. Received status code 403 from server: Forbidden
```

**Comment by raboof** [comment]
I think Travis (or at least some of their nodes) are being throttled/blacklisted by maven central. I'll retrigger those builds.

**Comment by raboof** [comment]
Refs #790

**Pull request merged**
