### PR TITLE
Spell 'gRPC' with lowercase 'g'

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by patriknw** [comment]
+1

Interesting that their official logo is with capital letters, but text is gRPC: https://grpc.io/docs/

**Comment by renatocaval** [comment]
I guess the reason why they have a logo with all uppercase is because of the arrow decoration they have crossing it. If it was was a lowercase g, it won't align correctly. Pure graphical design issue.

**Comment by raboof** [comment]
Bah, form should follow function :laughing:

**Comment by patriknw** [comment]
Yeah, completely unacceptable oversight. We should submit a PR. ;-)

**Pull request merged**
