### PR TITLE
Fix #636 by publishing bat scripts for Windows

### LINKED ISSUE #636: Akka grpc gradle plugin: Could not find akka-grpc-codegen_2.12-assembly.bat
### Versions used 
OS: Windows 10 x64
Gradle version: 5.5.1
JDK: 11
com.lightbend.akka.grpc.gradle: 0.7.0

Akka version: 2.5.22

### Expected Behavior
Gradle should be able to recognize the BAT file generated by plugin.

### Actual Behavior
The BAT file that is generated right next to assembly jar in `.gradle/cache` is not recognized by gradle. 

### Relevant logs

> Task :extractIncludeProto UP-TO-DATE
> Task :extractProto UP-TO-DATE
> Task :generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateProto'.
> Could not resolve all files for configuration ':protobufToolsLocator_akkaGrpc'.
   > Could not find akka-grpc-codegen_2.12-assembly.bat (com.lightbend.akka.grpc:akka-grpc-codegen_2.12:0.7.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/lightbend/akka/grpc/akka-grpc-codegen_2.12/0.7.0/akka-grpc-codegen_2.12-0.7.0-assembly.bat

### How to reproduce

Apply plugin to your gradle project, run `gradlew gP`

### PR DESCRIPTION
**Pull request by mlangc**
This PR attempts to fix #636 by publishing a bat script, that references the assembly JAR. I've only tested this with `publishM2` so far. To be sure that this works, I would have to publish to a remote repo, wipe all local repos, and verify that everything gets properly resolved by gradle. I'm going to do this next week, unless anyone does so before.

Apart from that I would like to have your feedback on the taken approach.

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by mlangc** [comment]
I've published a version of akka-grpc with this PR applied here: https://bintray.com/mlangc/maven-scratchpad

However, I cannot easily publish a test version of the gradle plugin. You can however work around this, by running `gradle publishToMavenLocal` in the `gradle-plugin` directory, after having checked out 29ec70bb3882a3bb660596d38ef06d54d7f67b22.

**Comment by mlangc** [comment]
Darn, there is still an issue, please don't try out anything yet.

**Comment by mlangc** [comment]
I've finally found out the the approach I was trying won't work out so easily, because the internal layout of the gradle cache gets into the way. Publishing a bat, that references a JAR simply won't work without major hacks. I'll try to modify this PR to publish a self contained bat instead.

**Comment by mlangc** [comment]
I've now modified the build to publish a self contained `bat` assembly for windows and published a version for testing to Bintray: https://bintray.com/mlangc/maven-scratchpad/akka-grpc/0.7.0%2B17-2ab0fe01

You can test it as explained above, but by using the commit 2ab0fe0157d646c318a92e3b9f83b8ef84cfaddf. Note that I did not yet test this on Windows, as I haven't a Windows PC at my disposal until Monday. So you might as well wait till I have confirmed that this change works at least for me, unless you are in a hurry and want to have this PR merged as soon as possible.

**Comment by raboof** [comment]
> Note that I did not yet test this on Windows, as I haven't a Windows PC at my disposal until Monday. So you might as well wait with testing until I have confirmed that this change works at least for me

That sounds great! No rush, but I'll be happy to merge and release 0.7.1 with this change when you confirm it has the desired effect.

**Comment by mlangc** [comment]
I've just tested this on Windows, and it works for me. More details can be found in the commit message of 8abac2d1782b64cc031a7686cf9e18e81c9a2123.

**Pull request merged**
