### PR TITLE
Add a 'git status' to diagnose the dirty repo

### PR DESCRIPTION
**Pull request by raboof**
To diagnose #1050

### CODE REVIEW

**Comment by ignasi35** [comment]
This is not meant to be merged, is it? I mean, will the job where the issue manifests already run in the PR?

**Comment by raboof** [comment]
> This is not meant to be merged, is it? I mean, will the job where the issue manifests already run in the PR?

We only publish from master, so this will have to be merged to see the diagnostics

**Comment by ignasi35** [comment]
> > This is not meant to be merged, is it? I mean, will the job where the issue manifests already run in the PR?
> 
> We only publish from master, so this will have to be merged to see the diagnostics

How abou hacking the conditions so the PR build runs a `publishLocal` could save us the extra noise in `master`? Maybe too much work and potential for a false positive.

Merging.

**Comment by ignasi35** [comment]
> Merging.

... when green. 😅

**Pull request merged**
