### PR TITLE
Cross publishing for SBT 0.13

### PR DESCRIPTION
**Pull request by andreaTP**
With this I add compatibility with SBT 0.13.X
I would need some guidance (or someone who can take over) to properly integrate publishing and scripted testing (the testing framework looks pretty elaborated, I hadn't spent on it enough to have a grasp).

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Are we sure we want to maintain support for 0.13? (I understand that it may be interesting to some people but sbt 1.x has been out for quite a while)

**Comment by dwijnand** [comment]
Given sbt 0.13 itself is no longer supported (https://www.scala-sbt.org/0.13/docs/index.html) I don't think akka-grpc should endeavour to _start_ supporting it.

**Comment by TimMoore** [comment]
Yes, I would rather focus efforts on removing any remaining obstacles preventing people from moving to 1.x.

**Comment by andreaTP** [comment]
fair enough, I have had to make a try ....

**Pull request closed without merging**
