### PR TITLE
Scala2.13.0 rc2

### PR DESCRIPTION
**Pull request by raboof**
Refs #506 

Depends on:
* [ ] https://github.com/scalapb/ScalaPB/issues/586
* [ ] Either https://github.com/playframework/playframework/issues/9336 or #517

### CODE REVIEW

**Comment by dwijnand** [comment]
> * [ ]  Either [playframework/playframework#9336](https://github.com/playframework/playframework/issues/9336) or #517

https://github.com/playframework/playframework/releases/tag/2.8.0-M1 is out (http://repo1.maven.org/maven2/com/typesafe/play/play-server_2.13.0-RC2/2.8.0-M1/), just not announced.

**Comment by raboof** [comment]
That means requiring Play 2.8 though... we might not (yet?) want that?

**Comment by dwijnand** [comment]
I don't think we'll be developing more releases of akka-grpc/play-grpc for Play 2.7/Lagom 1.5.  Onwards and upwards.

**Comment by marcospereira** [comment]
Or we can wait since we plan to have Scala 2.13 for Play 2.7 (but we will backport and release only 2.13 is GA).

**Comment by dwijnand** [comment]
Differently to Akka 2.5/2.6, Play 2.8 won't be binary compatible with Play 2.7, so we'll probably want to upgrade akka-grpc/play-grpc for Play 2.8.  But we can also do that closer to Play 2.8 coming out rather than right now, if preferred.  (Not what I would do.)

**Comment by raboof** [comment]
superseded by #599

**Pull request closed without merging**
