### PR TITLE
Use new API and support plaintext

### PR DESCRIPTION
**Pull request by ignasi35**
References #1193

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Nice!

(I kinda want to port this feature to master because it's pretty separate from the akka-http-client work and grows the diff... perhaps I'll give that a shot tomorrow)

**Comment by ignasi35** [comment]
Good point. 

I'll rebase onto `master`. No worries.

**Comment by raboof** [comment]
> Good point.
> 
> I'll rebase onto `master`. No worries.

(that would also need porting https://github.com/akka/akka-grpc/pull/1174/commits/397ed444c8250b27832ed671a19dbb6bb4e9f588 - might be a matter of cherry-picking but I'm not sure)

**Comment by ignasi35** [comment]
Retargeted to `master`. refs #1175

**Comment by raboof** [comment]
Thanks for the retarget!

**Pull request merged**
