### PR TITLE
feat: autodetect scala version for akka grpc runtime

### PR DESCRIPTION
**Pull request by eshepelyuk**
References #1024 

This PR adds tests to gradle plugin but I don't know how to integrate them into CI \ CD process.
Please could you add a stage to run tests for plugin in your pipelines.

The PR is based not on master, but on #1041 
So this PR must be merged the last.

@ignasi35 @raboof

### CODE REVIEW

**Comment by raboof** [comment]
#1041 is now merged, looks like this now needs a rebase

**Comment by eshepelyuk** [comment]
> #1041 is now merged, looks like this now needs a rebase

Rebase is done. 

PS: I suppose you did squash and merge from GitHub while merging previous PR, right ?

**Comment by raboof** [comment]
> PS: I suppose you did squash and merge from GitHub while merging previous PR, right ?

yes that's correct

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
Travis is green but didn't report back (probably due to the recent github outages): https://travis-ci.org/github/akka/akka-grpc/builds/703175211

**Pull request merged**
