### PR TITLE
Update to grpc-java 1.14.0

### PR DESCRIPTION
**Pull request by raboof**
Refs #318

### CODE REVIEW

**Comment by ktoso** [comment]
Hmmm gradle failed

```
FAILURE: Build failed with an exception.
* Where:
Build file '/home/travis/build/akka/akka-grpc/gradle-plugin/build.gradle' line: 22
* What went wrong:
A problem occurred evaluating project ':akka-grpc-gradle-plugin'.
> String index out of range: -1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 24s
The command "sbt publishM2 && cd plugin-tester-java && ./gradlew --include-build ../gradle-plugin clean compileJava" exited with 1.
```

**Comment by raboof** [comment]
Ticketified travis gradle problem as #322

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by raboof** [comment]
I'll rebase

**Pull request merged**
