### PR TITLE
Remove gradle wrapper from the benchmark-java project

### PR DESCRIPTION
**Pull request by ignasi35**

### CODE REVIEW

**Comment by ignasi35** [comment]
OK TO TEST

**Comment by raboof** [comment]
failure seem like #846?

**Comment by ignasi35** [comment]
> failure seem like #846?

How do you relate #846 (a timeout) to https://travis-ci.org/akka/akka-grpc/jobs/660088515#L3934-L3967 (which seems to be a `Failure` when `Success` is expected)?

**Comment by raboof** [comment]
> > 
> 
> How do you relate #846 (a timeout) to https://travis-ci.org/akka/akka-grpc/jobs/660088515#L3934-L3967 (which seems to be a `Failure` when `Success` is expected)?

Someone must have restarted that build, it is now green.

I was referring to https://jenkins.akka.io:8498/job/akka-grpc-pr-validator/1348/ - however I see your branch is already on top of #846, and indeed looking closer it fixes the wrong test :laughing:

**Comment by raboof** [comment]
PLS BUILD

**Pull request merged**
